[tools]
bat = "latest"
eza = "latest"
fastfetch = "latest"
fzf = "latest"
go = "latest"
lazygit = "latest"
neovim = "latest"
rg = "latest"
zoxide = "latest"

[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
experimental = false
