[tools]
bat = "latest"
bun = "latest"
eza = "latest"
fastfetch = "latest"
fd = "latest"
fzf = "latest"
"github:tummychow/git-absorb" = "latest"
gemini-cli = "latest"
gh = "latest"
go = "latest"
lazydocker = "latest"
lazygit = "latest"
neovim = "latest"
node = "latest"
python = "latest"
rg = "latest"
ruby = "latest"
tmux = "latest"
zig = "latest"
zoxide = "latest"
jq = "latest"
codex = "latest"
heroku = "latest"
opencode = "latest"


[settings]
idiomatic_version_file_enable_tools = ["node", "ruby"]
